#pragma once

#include <map>
#include <string>

namespace esphome {
  namespace dlms {
    const std::map <std::string, std::string> MANUFACTURERS {
      {"AAA", "Aventies GmbH"},
      {"AAB", "Milas"},
      {"ABB", "ABB AB"},
      {"ABC", "Paya Energy"},
      {"ABN", "ABN Braun AG"},
      {"ABR", "ABB s.r.o."},
      {"ACA", "Acean"},
      {"ACB", "AcBel Polytech Inc."},
      {"ACC", "Accurate (Pvt) Ltd"},
      {"ACE", "Actaris, France. (Electricity)"},
      {"ACG", "Actaris, France. (Gas)"},
      {"ACH", "Acantho S.p.A."},
      {"ACL", "Aclara Meters UK Ltd"},
      {"ACN", "ACN Advanced Communications Networks SA"},
      {"ACS", "Tianjin Chuangshi Technology Developing CO. Ltd."},
      {"ACT", "Activis Metering GmbH"},
      {"ACW", "Actaris, France. (Water and Heat)"},
      {"ADA", "Andrea Informatique Sarl"},
      {"ADD", "“ADD-Production” S.R.L."},
      {"ADE", "Yantai Aerospace Delu Energy-saving Technology Co., Ltd."},
      {"ADF", "ADFweb.com S.r.l."},
      {"ADN", "Aidon Oy"},
      {"ADR", "Adrem Engineering SRL"},
      {"ADU", "Adunos GmbH"},
      {"ADV", "Advant sp. z o.o."},
      {"ADX", "ADD-Production S.R.L."},
      {"AEA", "Abam Electronic Alborz"},
      {"AEC", "Advance Electronics Company"},
      {"AEE", "Atlas Electronics"},
      {"AEG", "AEG"},
      {"AEI", "Ajay Electrical Industries"},
      {"AEL", "Kohler"},
      {"AEM", "S.C. AEM S.A."},
      {"AEN", "ADVANCED ENERGY MANAGEMENT SOLUTIONS LTD"},
      {"AER", "Aerzener Maschinenfabrik GmbH"},
      {"AES", "ALFANAR ELECTRICAL SYSTEM"},
      {"AFX", "Alflex Products"},
      {"AGE", "AccessGate AB"},
      {"AGT", "Agnitio Technologies Pvt Ltd"},
      {"AHV", "aventies GmbH"},
      {"AHX", "Sepanta Electronic Tabarestan"},
      {"AIC", "Avastu India Creations Pvt Ltd."},
      {"AIM", "Ningbo Aimei Meter Manufacture Co., Ltd."},
      {"ALC", "Zenner Gas S.r.l."},
      {"ALF", "Alfatech – Elektromed Elektronik"},
      {"ALG", "Algodue Elettronica srl"},
      {"ALH", "ALFANAR ELECTRICAL SYSTEM"},
      {"ALK", "Actislink Sp. z o.o."},
      {"ALL", "Allied Engineering Works Pvt. Ltd."},
      {"ALP", "Alphion India Private Limited"},
      {"ALR", "Algorab S.R.L."},
      {"ALT", "Amplitec GmbH"},
      {"ALV", "Alvicom Ltd."},
      {"AMB", "Würth Elektronik eiSos GmbH & Co. KG"},
      {"AMC", "Arch Meter Corporation"},
      {"AMD", "KEPID AMSTECH"},
      {"AME", "Avon Meters Pvt. Ltd."},
      {"AMG", "ANTE METER GROUP CO., LTD"},
      {"AMH", "AmiHo Ltd"},
      {"AMI", "AMI Tech(I) Pvt. Ltd"},
      {"AML", "Eon Electric Ltd."},
      {"AMP", "Ampy Automation Digilog Ltd"},
      {"AMR", "Actislink"},
      {"AMS", "Zhejiang Joy Electronic Technology Co.,Ltd"},
      {"AMT", "INTEGRA METERING AG"},
      {"AMX", "APATOR METRIX SA"},
      {"ANA", "Anacle Systems PTE LTD"},
      {"AND", "Andis, s.r.o."},
      {"ANZ", "Anhui Nari Zenith Electricity&Electronic CO.,LTD"},
      {"AOM", "Aquametro Oil & Marine AG"},
      {"AON", "ASTRON d.o.o."},
      {"APA", "Apator SA"},
      {"APL", "APLI s.r.o."},
      {"APO", "Apolis GmbH"},
      {"APR", "Apronecs Ltd"},
      {"APS", "Apsis Kontrol Sistemleri"},
      {"APT", "Apator SA"},
      {"APX", "Amplex A/S"},
      {"AQA", "ACTAQUA GmbH"},
      {"AQL", "Aqualoc"},
      {"AQM", "INTEGRA METERING AG"},
      {"AQN", "Aquantia S.r.l."},
      {"AQT", "Aquatherm sp.j. PPH."},
      {"AQU", "Aquamess Gmbh"},
      {"ARA", "Aranha Ltd."},
      {"ARC", "Arcelik AS"},
      {"ARD", "Arad Group Ltd"},
      {"ARF", "ADEUNIS RF"},
      {"ARG", "ARGO group of companies"},
      {"ARK", "Arkon Flow Systems, s.r.o"},
      {"ARM", "Arivus metering GmbH"},
      {"ARQ", "ARQIVA"},
      {"ARS", "ADD – Bulgaria Ltd"},
      {"ART", "Electrotécnica Arteche Smart Grid"},
      {"ARW", "Arrow Electronics India Pvt. Ltd"},
      {"ARX", "Aras Mercu Sdn. Bhd."},
      {"ASA", "Asac srl"},
      {"ASC", "A2A Smart City"},
      {"ASD", "AS DAQ SYSTEMS PVT LTD"},
      {"ASG", "Meter technology Company"},
      {"ASH", "Basic Electronics Company Limited"},
      {"ASJ", "ACCUMET SOLUTIONS"},
      {"ASM", "Adya Wifi Metering Pvt. Ltd."},
      {"ASR", "Erelsan Elektrik ve Elektronik"},
      {"AST", "ASTINCO Inc."},
      {"ATA", "Alcansar Ölçüm ve Otomasyon Sistemleri"},
      {"ATF", "AKTIF OTOMASYON LTD.STI."},
      {"ATI", "Analogics Tech India Ltd."},
      {"ATL", "Atlas Elektronik"},
      {"ATM", "Atmel Spain SAU"},
      {"ATS", "Atlas Sayaç Sanayi A.Ş."},
      {"AUR", "Aurum Europe B.V."},
      {"AUT", "Aiut Sp. z o.o."},
      {"AUX", "Ningbo Sanxing Smart Electric Co., Ltd."},
      {"AVA", "Avangard JSC"},
      {"AXI", "UAB „Axis Industries“"},
      {"AXS", "AXSEM AG"},
      {"AYS", "Euromet Ltd Stl"},
      {"AZE", "AZEL Electronics"},
      {"BAM", "Bachmann GmbH & Co KG"},
      {"BAR", "Bär Industrie Elektronik GmbH"},
      {"BAS", "BASIC INTELLIGENCE TECHNOLOGY CO.,LTD."},
      {"BBE", "Bentec Bhartia Engineers Pvt. Ltd."},
      {"BBS", "BBS Electronics"},
      {"BCE", "ShenZhen B.C Electronic CO. Ltd."},
      {"BCR", "Jiangsu Bingchen Electronics Co Ltd."},
      {"BEA", "Baer Energy Automation GmbH"},
      {"BEE", "Bentec India Limited"},
      {"BEF", "BEFEGA GmbH"},
      {"BEG", "begcomm Communication AB"},
      {"BEL", "Belassitsa AD"},
      {"BEN", "BEENIC GmbH"},
      {"BER", "Bernina Electronic AG"},
      {"BFW", "BFW Buero fuer Waermemesstechnik OHG"},
      {"BHG", "Brunata A/S"},
      {"BJY", "Beijing JOYO smart water meter co.,ltd."},
      {"BKB", "Boendekomfort AB"},
      {"BKO", "Beko Elektronik AS"},
      {"BKT", "Bekto Precisa"},
      {"BLM", "BELIMO Automation AG"},
      {"BLU", "Bluering"},
      {"BME", "Beifeng GmbH"},
      {"BMI", "Badger Meter Inc., 6116 E 15th St."},
      {"BMP", "BMETERS Polska Sp.z.o.o."},
      {"BMT", "BMETERS  srl"},
      {"BNR", "Beijing Banner Electric Co., Ltd."},
      {"BOV", "JiaXing Bove Intelligent Technology Co., Ltd"},
      {"BPM", "Aadharshila Mobility Solutions Pvt Ltd"},
      {"BRA", "Brandes GmbH"},
      {"BRC", "BRICK4U GmbH"},
      {"BRN", "Bruntab Energy LTD."},
      {"BRT", "BEREKET TEKNOLOJİK ÖLÇÜM SİSTEMLERİ BİL.ELK.İNŞ.İTH.İHR.SAN VE TİC LTD.ŞTİ"},
      {"BSC", "Sanaye Sanjesh Energy Behineh Sazan Toos"},
      {"BSD", "BSED UG"},
      {"BSE", "Basari Elektronik A.S."},
      {"BSI", "Bundesamt für Sicherheit in der Informationstechnik (BSI)"},
      {"BSM", "Bluestar Electrical Meter Research Institute"},
      {"BSP", "Byucksan Power Co. Ltd."},
      {"BSS", "Baylan Su Sayaçları"},
      {"BST", "BESTAS Elektronik Optik"},
      {"BSX", "BS-Messtechnik UG"},
      {"BTA", "Buta Elektromekanik A.Ş."},
      {"BTL", "BIT-LAB"},
      {"BTM", "Bharatech Smart Industrial Pvt Ltd"},
      {"BTR", "RIA-BTR Produktions-GmbH"},
      {"BTS", "Basari Teknolojik Sistemler AS"},
      {"BUR", "Bopp und Reuther Messtechnik GmbH"},
      {"BUY", "BUYI TECHNOLOGOY CO., LIMITED."},
      {"BXC", "Beijing Fuxing Xiao-Cheng Electronic Technology Stock Co., Ltd Xisanhuan Beilu"},
      {"BYD", "BYD Company Limited"},
      {"BYL", "Baylan"},
      {"BYW", "Baylan Water Meters"},
      {"BZR", "Gebr. Bauer GbR"},
      {"CAB", "Cabtronix AG"},
      {"CAD", "CADIS"},
      {"CAH", "MAEC – GROUPE CAHORS"},
      {"CAL", "Caleffi S.p.A."},
      {"CAR", "CARI Electronic"},
      {"CAT", "Cubes And Tubes OY"},
      {"CAV", "CaveTronic"},
      {"CBI", "Circuit Breaker Industries"},
      {"CBS", "CB Svendsen A/S"},
      {"CCP", "13348164 Canada Corp"},
      {"CCS", "Chetas Control Systems Pvt Ltd"},
      {"CDA", "Centre for Development of Advanced Computing"},
      {"CDL", "Customised Data Ltd."},
      {"CDT", "CENTRE FOR DEVELOPMENT OF TELEMATICS"},
      {"CEB", "Cebyc AS"},
      {"CED", "CEDARNET"},
      {"CEG", "Consolinno Energy GmbH"},
      {"CEL", "Creative Electronics (Pvt) Ltd"},
      {"CEM", "YAVUZ METAL SANAYI VE TICARET A.S."},
      {"CET", "Cetinkaya Aydinlatma"},
      {"CGC", "Contor Group S.A."},
      {"CGO", "Cavagna Group S.p.A"},
      {"CHC", "CHUN-IL INSTRUMENT CO.,LTD"},
      {"CHE", "Shandong Chenhui Electronic Technology Co., Ltd."},
      {"CHM", "Chung-Hsin Electric and Machinery Manufacturing Corp. "},
      {"CHS", "Smart Services International Sagl"},
      {"CIC", "CHALLENGE INDUSTRIAL CO., LTD"},
      {"CIR", "Circutor"},
      {"CJS", "CJS Technology Ltd"},
      {"CKT", "CKT Elektrik Elektronik Sanayi ve Ticaret A.Ş"},
      {"CLA", "3g celllabs private limited"},
      {"CLB", "CMC S.r.l."},
      {"CLE", "Shen Zhen Clou Electronics Co Ltd. "},
      {"CLO", "Clorius  Raab Karcher Energi Service A/S"},
      {"CLS", "Celsa Messgeräte GmbH"},
      {"CLT", "Zhuhai S.E.Z. Calintech Electric Co., Ltd."},
      {"CLX", "CLK IPEKYOLU LOJISTIK VE TICARET A.Å."},
      {"CLY", "Clayster AB"},
      {"CMC", "CMC EKOCON d.o.o."},
      {"CMP", "CM Partner Inc"},
      {"CMS", "CMS Computers Limited"},
      {"CMT", "CMOSTEK MICROELECTRONICS CO., LTD."},
      {"CMV", "Comverge, Inc."},
      {"CNM", "COSTEL"},
      {"CNU", "CNU Global"},
      {"COH", "COHEAT Ltd, Future Business Centre"},
      {"COM", "COMMON S.A."},
      {"CON", "Conlog"},
      {"CPG", "CentraPlus GmbH"},
      {"CPL", "CPL CONCORDIA Soc.Coop."},
      {"CPO", "C3PO S.A."},
      {"CPS", "CAPITAL POWER SYSTEMS LIMITED"},
      {"CQC", "Yueqing Qicheng Electric Co., Ltd"},
      {"CRD", "CRDM DEVELOPPEMENTS"},
      {"CRT", "CRDM Technology"},
      {"CRW", "Xuzhou Runwu Science and Technology Development Co. Ltd."},
      {"CRX", "Corinex Communications Corp."},
      {"CRY", "Crystal Power"},
      {"CSC", "CHUBUSEIKI Co., LTD."},
      {"CSL", "Comsel System Ltd"},
      {"CSP", "CSP – Innovazione nelle ICT"},
      {"CTE", "COSTER T.E. S.p.A."},
      {"CTL", "Cyan Technology Ltd"},
      {"CTQ", "Control-Q b.v"},
      {"CTR", "Contar – Electronica Industrial"},
      {"CTT", "DLMS User Association Conformance"},
      {"CTX", "Contronix GmbH"},
      {"CUC", "Cuculus GmbH"},
      {"CUR", "CURRENT Group, LLC"},
      {"CWA", "CompWell AB"},
      {"CWI", "Cewe Instrument AB"},
      {"CWV", "CMEC Electric Import & Export Co. Ltd"},
      {"CYE", "Quanzhou Chiyoung Electronics Technology Co. Ltd."},
      {"CYI", "QUANZHOU CHIYOUNG INSTRUMENT CO., LTD"},
      {"CYN", "Cynox, Weinart Engineering"},
      {"CZA", "Contadores de Agua de Zaragoza S.A."},
      {"CZM", "Cazzaniga S.p.A."},
      {"DAE", "DAE Srl"},
      {"DAF", "Daf Enerji Sanayi ve Ticaret A.S."},
      {"DAN", "Danubia"},
      {"DBE", "Decibels Electronics P Ltd, Decibels Electronics Pvt Ltd."},
      {"DCD", "Delhi Control Devices Pvt. Ltd."},
      {"DCO", "diaeco wave company"},
      {"DDE", "D&D Elettronica srl"},
      {"DDI", "DD Infraventures Pvt. Ltd."},
      {"DDL", "DONGDO LMS"},
      {"DEA", "Dea HT srl"},
      {"DEC", "DECODE d.o.o. Data Communications"},
      {"DEL", "DELTAMESS DWWF GmbH"},
      {"DEN", "Ducati Energia"},
      {"DES", "Desi (Alarms) Ltd"},
      {"DEV", "Develco Products"},
      {"DFE", "Dongfang Electronics Co., Ltd."},
      {"DFS", "Danfoss A/S"},
      {"DGC", "Digicom S.p.A."},
      {"DGI", "Digi International Inc."},
      {"DGM", "Diehl Gas Metering GmbH"},
      {"DGY", "Discovergy GmbH"},
      {"DHA", "Shanghai dahua measuring&auto control instruments manufactory"},
      {"DHQ", "YIDU Smart Technology ( Beijing ) Co.,Ltd."},
      {"DIE", "Dielen GmbH"},
      {"DIG", "Digutal Request GmbH"},
      {"DIL", "DECCAN INFRATECH LIMETED"},
      {"DJA", "De Jaeger Automation bvba"},
      {"DKY", "Electric Power Research Institute of Guangdong Power Grid Corporation"},
      {"DLX", "Delixi Group Instruments & Meters Co.,ltd"},
      {"DMC", "DMC International"},
      {"DME", "DIEHL Metering"},
      {"DMO", "BEENIC GmbH"},
      {"DMP", "DM Power Co., Ltd"},
      {"DMS", "Digilog Micro Solutions Private Limited"},
      {"DNB", "Dana Sanjesh Ab o Bargh (Danaab)"},
      {"DNO", "DENO d.o.o."},
      {"DNT", "Dr Neuhaus Telekommunikation GmbH"},
      {"DNV", "DNV GL"},
      {"DOJ", "Suzhou Dojustek Intelligent Technology Co.,Ltd."},
      {"DOM", "Domat Control System"},
      {"DOS", "Metsec Cables Ltd."},
      {"DPM", "DELTA PRIMA METERING SDN. BHD."},
      {"DPP", "DECCAN POWER PRODUCTS PVT. LTD."},
      {"DRC", "DURECOM Co., Ltd."},
      {"DRT", "DRESSER Italia S.r.l."},
      {"DSE", "Digitech Systems and Engineering Private Limited"},
      {"DST", "Shenzhen Donsun Technology Co. Ltd."},
      {"DUA", "DLMS User Association"},
      {"DUS", "Dresser Utility Solutions GmbH"},
      {"DVG", "Device GmbH"},
      {"DVL", "devolo AG"},
      {"DWY", "Dwyer Instruments, LLC"},
      {"DWZ", "Lorenz GmbH & Co. KG"},
      {"DZG", "DZG Metering GmbH"},
      {"EAA", "Electronic Afzar Azma"},
      {"EAD", "EAD Energieabrechnungssysteme GmbH"},
      {"EAH", "Endress+Hauser"},
      {"EAS", "EAS Elektronik San. Tic. A.S."},
      {"EBE", "Ebeco AB"},
      {"EBK", "Biesenthal GmbH"},
      {"EBV", "EBV Elektronik GmbH & Co KG"},
      {"EBZ", "eBZ GmbH"},
      {"ECA", "ECO ADAPT"},
      {"ECC", "Energycare Company"},
      {"ECH", "Networked Energy Services Corporation"},
      {"ECL", "Electronics Corporation of India Ltd"},
      {"ECM", "Ecomess Sp. z o. o."},
      {"ECO", "Engie BtoC (Smart program)"},
      {"ECS", "Herholdt Controls srl"},
      {"EDI", "Enel Distribuzione S.p.A, Via Ombrone, 2, Rome"},
      {"EDM", "EDMI Pty. Ltd."},
      {"EEC", "ESCO Sp. z o.o."},
      {"EEE", "3E s.r.l."},
      {"EEM", "Electrify Energy Pvt. Ltd."},
      {"EEO", "Eppeltone Engineers Pvt Ltd"},
      {"EEP", "ELECTRONET EQUIPMENT PVT LTD"},
      {"EES", "Eletra Industria e Comercio de Medidores Elétricos"},
      {"EFA", "EFACEC Engenharia e Sistemas SA"},
      {"EFE", "Engelmann Sensor GmbH"},
      {"EFI", "Efimatic Iberica"},
      {"EFN", "EFEN GmbH"},
      {"EFR", "Europäische Funk-Rundsteuerung"},
      {"EFS", "EFSYS"},
      {"EGA", "eGain International AB"},
      {"EGC", "Ekbatan Gas Control"},
      {"EGD", "EcoGuard AB"},
      {"EGM", "Elgama-Elektronika Ltd"},
      {"EGT", "Enegate Co.,Ltd."},
      {"EGW", "Enermess Energie Mess- und Servicedienste GmbH"},
      {"EGY", "Egyptian Smart Meter Company"},
      {"EHL", "Secure Meters Limited"},
      {"EIE", "Ei Electronics"},
      {"EIG", "Eigensonne GmbH"},
      {"EIP", "Elmeasure India Pvt. Ltd"},
      {"EIT", "EnergyICT NV"},
      {"EKA", "Eka Systems"},
      {"EKF", "EKF"},
      {"EKO", "EKOLIS"},
      {"EKS", "DİCLE KÖK ENERJİ YATIRIM A.Ş"},
      {"EKT", "PA KVANT J.S."},
      {"ELC", "CJSC " EMIS ""},
      {"ELD", "Elektromed Elektronik Ltd"},
      {"ELE", "Elster Electricity LLC"},
      {"ELG", "Elgas s.r.o."},
      {"ELL", "Energy Plus"},
      {"ELM", "Elektromed Elektronik Ltd"},
      {"ELO", "ELO Sistemas Eletronicos S.A."},
      {"ELP", "ElectroPlus"},
      {"ELQ", "ELEQ b.v."},
      {"ELR", "Elster Metering Limited"},
      {"ELS", "Elster GmbH"},
      {"ELT", "ELTAKO GmbH"},
      {"ELV", "Elvaco AB"},
      {"EMB", "Embit s.r.l."},
      {"EMC", "Embedded Communication Systems GmbH"},
      {"EME", "SC. Electromagnetica SA"},
      {"EMF", "IT-Beratung Energiemanagement Flammang"},
      {"EMH", "EMH metering GmbH & Co. KG (formerly EMH Elektrizitatszahler GmbH & CO KG)"},
      {"EMI", "Entorno Inteligente de Medición S.L."},
      {"EML", "Emlite ltd"},
      {"EMM", "Email Metering"},
      {"EMO", "Enermet"},
      {"EMR", "CJSC “Energomera”"},
      {"EMS", "EMS-PATVAG AG"},
      {"EMT", "Elster Messtechnik GmbH"},
      {"EMU", "EMU Elektronik AG"},
      {"ENC", "ENSYCO ETHIOPIA ELECTRICITY METER  MANUFACTURING PLC"},
      {"END", "ENDYS GmbH"},
      {"ENE", "ENERDIS"},
      {"ENG", "ENER-G Switch2 Ltd"},
      {"ENH", "ENMAS GmbH"},
      {"ENI", "entec innovations GmbH"},
      {"ENL", "ENEL d.o.o."},
      {"ENN", "Enernet"},
      {"ENO", "ennovatis GmbH"},
      {"ENP", "“Kiev Polytechnical Scientific Research”"},
      {"ENR", "Energisme"},
      {"ENS", "ENSO NETZ GmbH"},
      {"ENT", "ENTES Elektronik"},
      {"ENX", "Enetronx GmbH"},
      {"EPI", "EPI-USE AFRICA"},
      {"EPL", "Escorts Pakistan Limited"},
      {"ERE", "Enermatics Energy (PTY) LTD"},
      {"ERI", "Easun Reyrolle Limited"},
      {"ERL", "Erelsan Elektrik ve Elektronik"},
      {"ERN", "Ericsson Telecomunicazioni S.p.A"},
      {"ERS", "Eurosys OOD"},
      {"ERW", "Everrenew Energy Pvt. Ltd."},
      {"ESA", "ESAC srl"},
      {"ESC", "EDMI (Shenzhen) CO., Ltd"},
      {"ESD", "Edelstrom Electronic Devices and Designing LLC"},
      {"ESE", "ESE Nordic AB"},
      {"ESG", "ESG CO.,LTD."},
      {"ESH", "EMSYCON GmbH"},
      {"ESI", "Monosan Monofaze Elektrik Motorlari"},
      {"ESM", "Monosan Monofaze Elektrik Motorlari"},
      {"ESN", "Zhejiang Eastron Electronic Co., Ltd."},
      {"ESO", "Monosan Monofaze Elektrik Motorlari"},
      {"ESP", "EFICAA ENSMART SOLUTIONS PRIVATE LIMITED"},
      {"ESR", "Ensor AG"},
      {"ESS", "Energy Saving Systems LTD."},
      {"ESV", "ESKA VALVE"},
      {"ESY", "EasyMeter GmbH"},
      {"ETD", "Energy Team S.p.A"},
      {"ETK", "ELTEK BROJILA d.o.o."},
      {"ETO", "Sphere of economical technologies LTd"},
      {"ETP", "Energotechnica Llc"},
      {"EUE", "E+E Electronic"},
      {"EUR", "Eurometers Ltd"},
      {"EUS", "Ebeling und Sohn GmbH & Co. KG"},
      {"EVD", "DREWAG NETZ GmbH"},
      {"EVK", "EV KUR ELEKTRIK"},
      {"EVL", "Geothermique Ltd"},
      {"EWA", "EWATTCH"},
      {"EWE", "EWE AG"},
      {"EWG", "EWG DOO"},
      {"EWS", "ENLESS WIRELESS"},
      {"EWT", "Elin Wasserwerkstechnik"},
      {"EXS", "exceeding solutions GmbH"},
      {"EXT", "LOTRIČ Metrology, Ltd."},
      {"EYE", "Eco-eye Ltd"},
      {"EYT", "Enerlyt Potsdam GmbH"},
      {"FAC", "Fireangel Safety Technology Ltd"},
      {"FAE", "Fae Technology Company"},
      {"FAN", "Fantini Cosmi S.p.A."},
      {"FAR", "FARAB"},
      {"FAS", "FAST S.P.A."},
      {"FED", "Federal Elektrik"},
      {"FEM", "Fortune Electric"},
      {"FFD", "Fast Forward AG"},
      {"FID", "Fi Muhendislik Ltd."},
      {"FIM", "Frodexim Ltd"},
      {"FIN", "Finder GmbH"},
      {"FIO", "Pietro Fiorentini"},
      {"FLA", "FLASH ELECTRONICS (INDIA) PVT LTD"},
      {"FLD", "Fludia"},
      {"FLE", "XI‘AN FLAG ELECTRONIC CO. LTD"},
      {"FLG", "FLOMAG s.r.o."},
      {"FLO", "Flonidan A/S"},
      {"FLS", "FLASH o.s"},
      {"FLU", "SHANDONG FEILONG INSTRUMENT CO."},
      {"FLW", "Fluidwell bv"},
      {"FLX", "FLEXIM Flexible Industriemesstechnik GmbH"},
      {"FMG", "Flow Meter Group"},
      {"FML", "Siemens Measurements Ltd. (Formerly FML Ltd.)"},
      {"FMM", "F.IMM s.r.l."},
      {"FNF", "FlowSystem"},
      {"FNX", "Flownetix Ltd"},
      {"FPL", "fifthplay NV"},
      {"FPR", "F-Pribor LLC"},
      {"FRC", "Friendcom Technology Co.,Ltd."},
      {"FRE", "Frer Srl"},
      {"FRU", "OJSC NRPA FRUNZE"},
      {"FSE", "Flecto Sense"},
      {"FSP", "Finmek Space S.p.A."},
      {"FST", "FieldServer Technologies"},
      {"FSY", "FlowService"},
      {"FTL", "Tritschler GmbH"},
      {"FUS", "Fuccesso"},
      {"FUT", "first:utility"},
      {"FWS", "FW Systeme GmbH"},
      {"FZK", "FUNZIN.Co. Ltd "},
      {"GAT", "GEPDEC SMART TECHNOLOGY PRIVATE LIMITED"},
      {"GAV", "Carlo Gavazzi Controls S.p.A."},
      {"GBJ", "Grundfoss A/S"},
      {"GCE", "Genergica"},
      {"GCG", "Goldcard Smart Group Co.,Ltd."},
      {"GDC", "GADICO TECNOLOGIA LTDA"},
      {"GDS", "InnoSense AG"},
      {"GEC", "GEC Meters Ltd."},
      {"GEE", "GE Energy"},
      {"GEL", "Industrial Technology Research Institute"},
      {"GEN", "Goerlitz AG, Germany"},
      {"GEO", "Green Energy Options Limited"},
      {"GEP", "GEPDEC INFRATECH LIMITED"},
      {"GET", "Genus Electrotech Ltd."},
      {"GEX", "Global Evolution Lighting"},
      {"GFM", "GE Fuji Meter Co.,Ltd."},
      {"GIL", "Genus Innovations Limited"},
      {"GIN", "Gineers Ltd."},
      {"GIO", "G. GIOANOLA S.r.l."},
      {"GLM", "GETRALINE"},
      {"GLO", "NetLand Sp. z o.o."},
      {"GLX", "Vietnam Electrical Equipment Joint Stock Corporation"},
      {"GMC", "GMC-I Messtechnik GmbH"},
      {"GME", "Global Metering Electronics"},
      {"GMM", "Gamma International Egypt"},
      {"GMS", "Gity Madara Sepahan"},
      {"GMT", "GMT GmbH"},
      {"GNP", "GEPDEC ENERGY PVT LTD"},
      {"GNY", "JiangSu GuoNeng Instrument Technology CO.,LTD"},
      {"GOE", "Genus Power Infrastructures Ltd."},
      {"GPM", "Gram Power (India) Pvt. Ltd."},
      {"GPT", "GINTAI POWER TECHNOLOGY CO., LTD"},
      {"GRA", "Grässlin GmbH"},
      {"GRD", "Greenradio"},
      {"GRE", "GE2, Green Energy Electronics"},
      {"GRI", "Grinpal Energy Management"},
      {"GRN", "GREEN ENS Co., Ltd."},
      {"GRP", "GlobalRnD sp. z o.o."},
      {"GRS", "Garderos GmbH"},
      {"GRU", "G.GURU  Co., Ltd."},
      {"GRX", "Gurux Ltd"},
      {"GSD", "Genesis Smart Devices Private Limited"},
      {"GSE", "Gridspertise S.r.l."},
      {"GSP", "Ingenieurbuero Gasperowicz"},
      {"GSS", "R&D Gran-System-S LLC"},
      {"GST", "Shenzhen Golden Square Technology Co.,Ltd."},
      {"GTE", "GREATech GmbH"},
      {"GTM", "G2 misuratori S.r.l."},
      {"GTR", "Globaltronics for Electronics S.A.E."},
      {"GTS", "GIGATRONIK Stuttgart GmbH"},
      {"GUH", "ShenZhen GuangNing  Industrial CO. Ltd."},
      {"GVL", "gAvilar"},
      {"GWF", "Gas- u. Wassermesserfabrik"},
      {"GWI", "George Wilson Industries, Aldermans Green Industrial Estate"},
      {"HAG", "Hager Electro GmbH"},
      {"HAK", "Hako, a.s."},
      {"HBY", "HENAN HUABIAO INSTRUMENT TECHNOLOGY Co., Ltd."},
      {"HCE", "Hsiang Cheng Electric Corp"},
      {"HCM", "Hidroconta S.A.U."},
      {"HDK", "Hydroko NV"},
      {"HDX", "Beijing TianRuiXiangDe Measuring Technology Co.,Ltd."},
      {"HDY", "Dalian hundao instrument Co. Ltd."},
      {"HEG", "Hamburger Elektronik Gesellschaft"},
      {"HEI", "Hydro-Eco-Invest SP. Z O.O."},
      {"HEK", "Hexing Technology Company Limited"},
      {"HEL", "Heliowatt"},
      {"HEM", "Hokkaido Electric Meter Industry Co."},
      {"HER", "Hermes Systems"},
      {"HEW", "Honeywell Integrated Technology (China) Co., Ltd."},
      {"HEX", "Shenzhen Hexcell Electronics Technology CO.,LTD"},
      {"HFI", "Nanjing Huiran Measurement&Control Technology Co. Ltd."},
      {"HFL", "HFIL Technologies Private Limited"},
      {"HFR", "SAERI HEAT METERING TECHNOLOGY CO.,LTD."},
      {"HGM", "HG meter a/s"},
      {"HHE", "HAUSHELD AG"},
      {"HHM", "Chongqing Huahong Metering Co.,Ltd."},
      {"HIE", "Shenzhen Holley South Electronics Technology Co., Ltd."},
      {"HIN", "huebner Informationselektronik"},
      {"HIT", "ABB Sp. z o.o."},
      {"HJM", "Huaihua Jiannan Machinery Factory Co.,Ltd"},
      {"HKK", "Hokuriku Instrumentation Co. Inc."},
      {"HLY", "Holley Metering Ltd"},
      {"HMI", "HMI Energy Co., Ltd."},
      {"HML", "Holley Technology Ltd., 181 WuChang Avenue"},
      {"HMS", "Hermes Systems"},
      {"HMT", "Hangzhou Meteronic Technology Co., Ltd."},
      {"HMU", "Hugo Müller GmbH & Co KG"},
      {"HND", "Shenzhen Hemei Group Co., Ltd."},
      {"HOE", "HOENTZSCH GMBH"},
      {"HOL", "Holosys d.o.o."},
      {"HON", "Honeywell Technologies Sarl"},
      {"HOY", "Holley Meters"},
      {"HPL", "HPL-Socomec Pvt. Ltd."},
      {"HPM", "HANGZHOU HPM COMPANY LIMITED"},
      {"HQL", "H.Q LAMPS MANUFACTURING CO PRIVATE LIMITED"},
      {"HRM", "Hefei Runa Metering Co., Ltd."},
      {"HRS", "HomeRider SA"},
      {"HSD", "Ningbo Histar Meter Technology Co.,Ltd."},
      {"HST", "HST Equipamentos Electronicos Ltda"},
      {"HSX", "HST GmbH"},
      {"HTC", "Horstmann Timers and Controls Ltd."},
      {"HTI", "Shandong Hetong Information Technology CO.,Ltd."},
      {"HTL", "Ernst Heitland GmbH & Co. KG, Erlenstr. 8-10"},
      {"HTS", "HTS-Elektronik GmbH"},
      {"HUK", "Helbeck & Kusemann GmbH & Co. KG"},
      {"HUM", "Humanlitech Ghana Limited"},
      {"HVG", "Hekatron Vertriebs GmbH"},
      {"HVT", "Helvatron AG"},
      {"HWC", "Qingdao Hiwits Meter Co.,Ltd."},
      {"HWM", "Beijing Hongwei Chaoda Instrument Manufacturing Co.,Ltd."},
      {"HWT", "Huawei Technologies Co. Ltd."},
      {"HXD", "Beijing HongHaoXingDa Meters CO.,LTD."},
      {"HXE", "Hexing Electrical Co. Ltd."},
      {"HXT", "HEXIN (HONGKONG) TECHNOLOGY CO., LIMITED"},
      {"HXW", "Hangzhou Xili Watthour Meter Manufacture Co. Ltd."},
      {"HYC", "Zhejiang Hengye Electronics Co.,Ltd"},
      {"HYD", "Hydrometer GmbH"},
      {"HYE", "Zhejiang Hyayi Electronic Industry Co Ltd."},
      {"HYG", "Hydrometer Group"},
      {"HYM", "Zhejiang Hengye Electronics Co.,Ltd"},
      {"HYS", "Hydrelis"},
      {"HYT", "Zhejiang Hengye Electronics Co.,Ltd"},
      {"HZC", "TANGSHAN HUIZHONG INSTRUMENTATION CO., LTD. "},
      {"HZI", "TANGSHAN HUIZHONG INSTRUMENTATION CO., LTD. "},
      {"HZZ", "Huizhou Zhongcheng Electronic Technology Co.,Ltd."},
      {"IAC", "INHEMETER AFRICA COMPANY LIMITED"},
      {"IBE", "IBOT ENERGY SYSTEMS INDIA PRIVATE LIMITED"},
      {"IBG", "ITI LIMITED, BANGALORE PLANT"},
      {"IBT", "İkom Bilişim Teknolojileri AŞ"},
      {"ICB", "Inscobee"},
      {"ICE", "Icoal incorporated"},
      {"ICK", "I&C Technology"},
      {"ICM", "Intracom"},
      {"ICP", "PT Indonesia Comnets Plus"},
      {"ICS", "ICSA (India) Limited"},
      {"ICT", "International Control Metering-Technologies GmbH"},
      {"ICU", "i-cube"},
      {"IDE", "IMIT S.p.A"},
      {"IDS", "IDS GmbH"},
      {"IEC", "leonnardo Corporation"},
      {"IEE", "I.E. Electromatic, S.L"},
      {"IEI", "Informage Energy Pvt. Ltd."},
      {"IEN", "Institute of Power Engineering"},
      {"IES", "Integrated Electronic Systems Lab Co., Ltd."},
      {"IFC", "infocon doo"},
      {"IFX", "Infineon Technologies"},
      {"IGM", "ITALGAS RETI"},
      {"IGR", "iGridS GmbH, Hebelweg 2"},
      {"IGS", "I.G.S.DATAFLOW S.r.l."},
      {"IHM", "Shenzhen Inhemeter Co., Ltd."},
      {"IID", "PT INDUSTRI TELEKOMUNIKASI INDONESIA (Persero)"},
      {"IIF", "Westenergie Metering GmbH "},
      {"IJE", "ILJIN Electric"},
      {"IJK", "IJENKO SA"},
      {"IKE", "IK Elektronik GmbH, Friedrichsgruener Str. 11-13, 08262"},
      {"IKM", "Ikom LTD"},
      {"IKS", "IKASIAN"},
      {"IMC", "Iranmadar"},
      {"IME", "Fellows s.c.ul. "},
      {"IMR", "iMeter LLC"},
      {"IMS", "IMST GmbH"},
      {"IMT", "INTEGRA METERING AG"},
      {"IMZ", "iMezr Innovations Pvt Ltd"},
      {"INC", "Incotex"},
      {"IND", "INDRA SISTEMAS"},
      {"INE", "INNOTAS Elektronik GmbH"},
      {"INF", "Infometric"},
      {"INI", "Altero AB"},
      {"INM", "Inepro Metering BV"},
      {"INN", "INNEXIV, Inc."},
      {"INO", "Indotech Switchgear & Controls(Delhi) Pvt. Ltd"},
      {"INP", "INNOTAS Produktions GmbH"},
      {"INS", "INSYS MICROELECTRONICS GmbH"},
      {"INT", "Infranet Technologies GmbH "},
      {"INV", "Sensus Metering Systems"},
      {"INX", "Innolex Engineering BV"},
      {"ION", "Ionics EMS Inc"},
      {"IOT", "Trilliant Networks Inc"},
      {"IPD", "IPD Industrial Products Australia"},
      {"IQO", "Kwhiq"},
      {"IQS", "IQ Systems (Pty) Ltd"},
      {"IRE", "IREN Energia S.p.A."},
      {"ISA", "Isabellenhütte Heusler GmbH & Co. KG"},
      {"ISE", "INESH SMART ENERGY (P) LTD."},
      {"ISF", "Investcom Szymon Fiedorowicz"},
      {"ISI", "Akcionarsko Drustvo “Insa” Industrija Satova"},
      {"ISK", "Iskraemeco"},
      {"ISO", "Isoil Industria spa"},
      {"ISS", "Iskra d.d."},
      {"IST", "Ista"},
      {"ISW", "iSAtech water GmbH"},
      {"ITA", "iTrona GmbH"},
      {"ITB", "Itron Solucoes para Energia e Agua Ltda."},
      {"ITC", "INTECH TUNISIE"},
      {"ITE", "ITRON (Electricity)"},
      {"ITF", "ITF Fröschl GmbH"},
      {"ITG", "ITRON (Gas)"},
      {"ITH", "INTELTEH d.o.o."},
      {"ITI", "ITRON Asia"},
      {"ITK", "Itron GmbH"},
      {"ITL", "Indriya Technologies Pvt Ltd"},
      {"ITM", "Intelligent Metering Systems (Pvt.) Limited"},
      {"ITP", "M/s ITI LIMITED."},
      {"ITR", "Itron Inc"},
      {"ITS", "ITRON Australasia Pty Ltd"},
      {"ITU", "ITRON United States, Itron Inc "},
      {"ITW", "ITRON (Water)"},
      {"ITX", "IDEAL TECHNICAL SOLUTIONS"},
      {"ITZ", "ITRON South Africa"},
      {"IUS", "IUSA SA DE CV "},
      {"IVY", "IVY-metering"},
      {"IWD", "Inkwell Data"},
      {"IWK", "IWK Regler und Kompensatoren GmbH"},
      {"IYI", "KAYI ENERGY Hacettepe Üniversitesi"},
      {"IZE", "iZenze AB"},
      {"JAC", "Jay Autocomponents Limited"},
      {"JAN", "Janitza electronics GmbH"},
      {"JBF", "Beijing jingyibeifang instrument limited company"},
      {"JCE", "Janz – Contadores de Energia SA"},
      {"JED", "JED Co Ltd"},
      {"JGD", "tianjin guangdaweiye measuring instrument technology Co.,Ltd"},
      {"JGF", "Janz – Contagem e Gestao de Fluidos SA"},
      {"JGH", "ITSQUARE CO.,LTD"},
      {"JHA", "Zhejiang JiaHe Instrument CO.,Ltd"},
      {"JHM", "Changzhou Jianhu Intelligentize Meter Co.,Ltd."},
      {"JJN", "BeiJing Fine&Clean Enery Technology Co.,Ltd"},
      {"JKW", "QingdaoJakewill Energy Technology Co.,Ltd."},
      {"JMT", "JM-TRONIC Sp. z o.o."},
      {"JNC", "NINGBO JIANAN ELECTRONICS CO.,LTD."},
      {"JND", "J&D Electronics CO.,Ltd"},
      {"JNJ", "JNJ POWERCOM SYSTEMS LTD"},
      {"JOY", "Zhejiang Joy Electronic Technology Co., Ltd."},
      {"JPM", "JPM INDUSTRIES LIMITED"},
      {"JSM", "Jining Goldwater Science&Technology Co.,Ltd."},
      {"JSO", "Schlösser Armaturen GmbH & Co. KG"},
      {"JUM", "JUMO GmbH & Co. KG"},
      {"JWH", "TIANJIN WANHUA CO.,LTD."},
      {"JWR", "Shandong jingwei telecommunications equipment co., LTD."},
      {"JWS", "Wesson energy-saving technology (tianjin) co., LTD."},
      {"JYS", "Beijing Jingyuan instrument limited company"},
      {"KAA", "Kamstrup A/S"},
      {"KAC", "АО "КАСКАД"},
      {"KAL", "Kallenbach Elektronik GmbH"},
      {"KAM", "Kamstrup Energi A/S"},
      {"KAR", "Keskar Vana Metal Mak. Ltd. Sti."},
      {"KAS", "Kamstrup A/S"},
      {"KAT", "KATHREIN-Werke KG"},
      {"KAW", "Kamstrup A/S"},
      {"KBH", "K. Biesinger GmbH"},
      {"KBK", "KBK ELECTRONICS (PVT) LTD."},
      {"KBN", "Alpamis IT Ltd."},
      {"KDN", "KADEN-VODOMĚRY, s.r.o."},
      {"KDS", "Kedros a.s."},
      {"KEE", "Keewe.co ltd."},
      {"KEL", "KELEMINIC d.o.o."},
      {"KER", "KERMS UG (haftungsbeschränkt)"},
      {"KES", "Kavosh Electronic Sepahan"},
      {"KFM", "Shenzhen Kaifa Technology （Chengdu） Co., Ltd."},
      {"KFM", "Shenzhen Kaifa Technology Co., Ltd."},
      {"KGE", "Guangzhou Keli General Electric Co., Ltd."},
      {"KHL", "Kohler"},
      {"KIG", "Kiwigrid GmbH Kleiststraße 10a-c"},
      {"KJN", "Radniroo Industrial Co"},
      {"KKE", "KK-Electronic A/S"},
      {"KKG", "Katronic AG & Co. KG"},
      {"KLE", "SHIJIAZHUANG KELIN ELECTRIC CO., LTD."},
      {"KLK", "Kerlink"},
      {"KMB", "Kamstrup A/S"},
      {"KMT", "Krohne Messtechnik GmbH"},
      {"KNI", "zhangzhou keneng electrical equipment co., ltd"},
      {"KNX", "KONNEX-based users (Siemens Regensburg)"},
      {"KPD", "Korea Electric Power Industrial Development Co., Ltd."},
      {"KRO", "Kromschroder"},
      {"KRT", "Karat"},
      {"KSM", "Korea Testing Certification"},
      {"KST", "Kundo SystemTechnik GmbH"},
      {"KSY", "KUNDO SystemTechnik GmbH"},
      {"KTC", "Kerman Tablo Co"},
      {"KTL", "Korea Testing Laboratory"},
      {"KUK", ""KYRGYZ UNAA KURUUSH" LLC"},
      {"KWH", "Zhejiang Songxia Electric Meter Co., Ltd"},
      {"KZK", "KŘIŽÍK s.r.o."},
      {"LAC", "Heinz Lackmann GmbH & Co KG"},
      {"LAI", "Hangzhou LAISON Technology Co.,LTD"},
      {"LAN", "Langmatz GmbH"},
      {"LAS", "Lansen Systems AB"},
      {"LCG", "Landis+Gyr Meter & System (Zhuhai) Co., Ltd,"},
      {"LCR", "ShanDong LiChuang Science and Technology Co.,Ltd."},
      {"LDE", "Shenzhen Londian Electrics Co., Ltd."},
      {"LEC", "Lectrotek Systems Pvt Ltd."},
      {"LEI", "PCP International Ltd"},
      {"LEM", "LEM HEME Ltd."},
      {"LES", "Lakshmi Electrical Control Systems Limited"},
      {"LET", "LAN ENGINEERING & TECHNOLOGIES"},
      {"LFS", "Payolcer Metering Devices"},
      {"LFX", "LoggerFlex Smart Devices Ltd."},
      {"LGA", "Landis+Gyr AG"},
      {"LGB", "Landis+Gyr Ltd."},
      {"LGC", "Landis+Gyr Equipamentos de Medição Ltda, Brasil"},
      {"LGD", "Landis+Gyr GmbH"},
      {"LGE", "Landis+Gyr PTE Ltd."},
      {"LGF", "Landis+Gyr Oy"},
      {"LGG", "Ningxia LGG Instrument Co., LTD"},
      {"LGI", "Landis+Gyr Ltd."},
      {"LGS", "Landis+Gyr (Pty) Ltd."},
      {"LGU", "LG Uplus Corp."},
      {"LGZ", "Landis+Gyr AG"},
      {"LHA", "Atlantic Meters"},
      {"LIN", "Ever Meter Co., Ltd"},
      {"LIT", "Punos Electronic AB"},
      {"LJP", "Lars Jansen Productions"},
      {"LLM", "LianYunGang LianLi·First Meter CO. LTD."},
      {"LMC ", "Lumacol s.r.o."},
      {"LMG", "Luftmeister GmbH"},
      {"LML", "LUMEL"},
      {"LMP", "LIN MAN POWER TECHNOLOGY,INC."},
      {"LMS", "LMS Services GmbH"},
      {"LNC", "Lancier Monitoring GmbH"},
      {"LNK", "Loenk F9"},
      {"LNT", "Schneider Electric India Private Limited "},
      {"LOB", "Lobaro GmbH"},
      {"LOG", "LOGAREX Smart Metering, s.r.o."},
      {"LOV", "Lovato Electric S.p.A."},
      {"LSC", "Lund Science AB"},
      {"LSE", "Landis & Staefa electronic"},
      {"LSK", "LS Industrial Systems Co Ltd."},
      {"LSP", "Landis+Gyr GmbH"},
      {"LSZ", "Siemens Building Technologies"},
      {"LTO", "Labtrino AB"},
      {"LUG", "Landis+Gyr GmbH"},
      {"LUN", "LUNA Elektrik Elektronik A.S."},
      {"LWT", "Lotus Wireless Technologies India Private Limited"},
      {"LYE", "Jiangsu Linyang Electronics Co. Ltd."},
      {"LZG", "Lackmann Zähler Gesellschaft mbH & Co. KG"},
      {"MAC", "RUDNAP Group Meter & Control"},
      {"MAD", "Maddalena S.p.A."},
      {"MAE", "Mates Elektronik Metin Ates"},
      {"MAG", "MAGNATECH Smart Grid Solutions Pvt. Ltd."},
      {"MAH", "MAHAM ELECTRONIC SAMA SANAT"},
      {"MAN", "Manthey GmbH"},
      {"MAT", "Mitsubishi Electric Automation"},
      {"MAX", "MAXMET Inc"},
      {"MBS", "MBS AG"},
      {"MCI", "METERING AND COMMUNICATIONS SOLUTIONS PRIVATE LIMITED"},
      {"MCP", "MPSE"},
      {"MCR", "MICRORISC"},
      {"MCS", "MetCom Solutions GmbH"},
      {"MDA", "PT.MELCOINDA"},
      {"MDE", "Diehl Metering Deutschland"},
      {"MDL", "Maddalena S.p.A."},
      {"MDX", "mdex AG"},
      {"MEC", "Mitsubishi Electric Corporation"},
      {"MED", "MAHARASHTRA STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED"},
      {"MEE", "Metron Europe"},
      {"MEH", "Mueller-electronic GmbH"},
      {"MEI", "Sensus Metering Systems"},
      {"MEL", "Mikroelektronika a.d"},
      {"MEM", "MEMS AG"},
      {"MES", "Electrometer Spain S.L.U."},
      {"MET", "METRA Energie-Messtechnik GmbH"},
      {"MEX", "Metrix Italia s.r.l."},
      {"MHT", "Mechatronic Meters srl"},
      {"MIC", "Microtronics Engineering GmbH"},
      {"MID", "MiDo Srl"},
      {"MII", "Apator Miitors ApS"},
      {"MIJ", "MAXWELL INDIA"},
      {"MIK", "Mikroklima s.r.o."},
      {"MIL", "Milur Smart System Limited liability company"},
      {"MIM", "Malaysian Intelligence Meters Sdn. Bhd."},
      {"MIR", "MIR Research and Production Association"},
      {"MIS", "Iskra MIS d.d"},
      {"MIT", "Sagemcom Energy & Telecom"},
      {"MIV", "MIVO Technology AB"},
      {"MKA", "mirakonta"},
      {"MKE", "MKEK Genel Mudurlugu Gazi Fisek (ELSA)"},
      {"MKL", "MAKEL Elektrik Malzemeleri"},
      {"MKS", "MAK-SAY Elektrik Elektronik"},
      {"MLQ", "MeterLinq"},
      {"MLR", "PKK Milandr"},
      {"MMC", "Modern Meters Co."},
      {"MMF", "MEMF Electrical Industries Co."},
      {"MMI", "MyMeterInfo"},
      {"MMM", "MATRICA Ltd"},
      {"MMP", "MATRIXMETERS PVT. LTD."},
      {"MMS", "Brunswick Bowling and Billiards UK Ltd"},
      {"MMT", "METMOTEC"},
      {"MNS", "MANAS Elektronik"},
      {"MNW", "MENOWATT GE SRL"},
      {"MOJ", "Mojec International"},
      {"MOS", "MOMAS SYSTEMS NIGERIA LIMITED"},
      {"MOT", "The Motwane Manufacturing Company Private Limited"},
      {"MPA", "Mega Power Automation International Limited"},
      {"MPL", "Metrona Polska Pomiary i Rozliczenia sp. z o.o."},
      {"MPR", "Michael Rac GmbH"},
      {"MPS", "Multiprocessor Systems Ltd"},
      {"MRN", "LLC "RPC "MEtRON"},
      {"MRT", "MIRTEK LTD."},
      {"MSB", "MISA SDN BHD"},
      {"MSE", "Mahashakti Energy Limited"},
      {"MSM", "MS-M Co., Ltd."},
      {"MSO", "Metiso"},
      {"MST", "Microsoft Taiwan Corporation"},
      {"MSY", "MAK-SAY Elektrik Elektronik Malzemeleri"},
      {"MTC", "Metering Technology Corporation"},
      {"MTD", "Removed - November 2006"},
      {"MTE", "The Egyptian German Co. for Water Meter Manufacturing (Metrotec Egypt)"},
      {"MTH", "njmeter"},
      {"MTI", "Microtech Industries Pakistan"},
      {"MTL", "Advance Metering technology Limited"},
      {"MTM", "Metrum Sweden AB"},
      {"MTN", "Merytronic 2012,S.L"},
      {"MTP", "Modern Transformers Pvt. Ltd."},
      {"MTR", "METER"},
      {"MTS", "MeteRSit S.r.L."},
      {"MTX", "Matrix Energy Pvt. Ltd."},
      {"MUK", "Meters UK Ltd, Whitegate, White Lund Trading Estate"},
      {"MWI", "Magic Wand Intelligent Systems"},
      {"MWU", "METRONA Union GmbH"},
      {"MXE", "Hangzhou MingX technology Co.,LTD"},
      {"MXM", "Maxim India Integrated Circuit Design Pvt Ltd."},
      {"MYS", "MODEMSYS S.L."},
      {"NAE", "Nanjing NengRui Automation Equipment Co., LTD."},
      {"NAR", "NARI Group Corporation-NARI Technology Development Co., Ltd"},
      {"NAS", "NAS Instruments OÜ"},
      {"NAS", "NAS Instruments OÜ"},
      {"NAT", "Natural Heat Ahorro Energetico SL"},
      {"NCK", "NC Korea"},
      {"NDF", "NÚCLEO DURO FELGUERA"},
      {"NDM", "Northern Design"},
      {"NEE", "Northern Electric Equipment Joint Stock Company"},
      {"NER", "Nero Electronics Ltd"},
      {"NES", "NORA ELK. MALZ. SAN. ve TİC. A.Ş."},
      {"NET", "Netatmo"},
      {"NGP", "Ngenic Poland Sp. z o.o."},
      {"NIK", "NIK-ELEKTRONIKA"},
      {"NIS", "Nisko Industries"},
      {"NJC", "NAMJUN Co Ltd"},
      {"NKS", "N-ERGIE Kundenservice GmbH"},
      {"NLI", "Next Level Integration GmbH"},
      {"NME", "SI-ART LLC"},
      {"NMG", "NMG S.A."},
      {"NMS", "Nisko Advanced Metering Solutions"},
      {"NMT", "Nova-met s.r.o."},
      {"NNT", "2N Telekomunikace a.s."},
      {"NOI", "NOITAC sp. z o.o. sp.k."},
      {"NOQ", "NorthQ"},
      {"NOV", "NovaTech LLC"},
      {"NPL", "CSIR-National Physical Laboratory"},
      {"NPS", "NEOPIS CO., LTD 4F"},
      {"NPT", "CJSC PROGTECH"},
      {"NRM", "Norm Elektronik"},
      {"NRN", "Neuron GmbH"},
      {"NRT", "Zavod Nartis Ltd."},
      {"NSE", "North Smart Equipment Co., Ltd"},
      {"NSP", "M/S N S Power"},
      {"NTC", "Nuri Telecom Co Ltd"},
      {"NTM", "Netinium"},
      {"NVD", "METER Ltd"},
      {"NVN", "NOVEN ENERGY AND ICT LTD."},
      {"NWG", "NINGBO WASSER GERAETE CO.,LTD."},
      {"NWM", "Ningbo Water Meter Co.Ltd."},
      {"NXG", "nexgen consultancy pvt ltd"},
      {"NXP", "NXP Semiconductors"},
      {"NYG", "Ningbo Yonggang Instrument Co. Ltd."},
      {"NYN", "Nanjing Yuneng Instrument Co Ltd."},
      {"NZR", "Nordwestdeutsche Zählerrevision Ing. Aug. Knemeyer GmbH & Co. KG"},
      {"OAS", "Omni Agate Systems"},
      {"OBC", "shandong oubiao information Technology. LTD"},
      {"OBE", "Obeo as"},
      {"OBR", "RMZ OBRIY LTD"},
      {"ODI", "OAS Digital Infrastructures Pvt. Ltd."},
      {"ODK", "Okinawa Denki Kogyo Co.,Ltd."},
      {"OEE", "ONUR Elektrik ve Elektronik"},
      {"OKN", "be.storaged"},
      {"OLI", "Olivetti S.p.A."},
      {"OMG", "Open Metering System Group – OMS-Group e. V."},
      {"OMS", "OMNISYSTEM Co., Ltd."},
      {"ONR", "ONUR Elektroteknik"},
      {"ONS", "ONUR Elektroteknik"},
      {"OPT", "Optec GmbH"},
      {"ORB", "ORBIS Tecnologia Electrica, SA"},
      {"ORM", "Ormazabal"},
      {"OSA", "Osaki Electric Co., Ltd.(Europe)"},
      {"OSB", "Ocea Smart Building"},
      {"OSC", "Oriental Sales Corporation"},
      {"OSK", "Osaki Electric Co Ltd. (Japan)"},
      {"OTM", "OTMetric"},
      {"OTS", "Shenzhen Oasis Technology Service Co., Ltd"},
      {"OYK", "GULLWING(TIANJIN)INDUSTRY DEVELOPMENGT CO.,LTD."},
      {"OZK", "Oz-kar Enerji"},
      {"PAD", "PadMess GmbH"},
      {"PAF", "FAP PAFAL S.A."},
      {"PAI", "PAIBOONKIJTHANA CO.,LTD"},
      {"PAK", "Paktim Energy Sp.zo.o."},
      {"PAN", "Panasonic Corporation"},
      {"PBR", "PFIFFNER do Brasil"},
      {"PCE", "Precise Electronics co.,LTD."},
      {"PCR", "Powercom"},
      {"PDE", "Pfiffner Deutschland GmbH"},
      {"PDX", "Paradox Engineering SA"},
      {"PEA", "PEA J.V. Company"},
      {"PEE", "Prantech Energy Solutions"},
      {"PEL", "Pak Elektron Ltd. (PEL)"},
      {"PEP", "POWRTEC ENERGY PVT. LTD."},
      {"PER", "Perry Electric"},
      {"PFI", "PFIFFNER Instrument Transformers Ltd"},
      {"PGE", "PayGo Energy, Inc"},
      {"PGP", "P.G.P. - Smart Sensing s.a."},
      {"PHL", "HangZhou PAX Electronic Technology Co., Ltd."},
      {"PHX", "Phoenix Systems sp z o.o."},
      {"PII", "PiiGAB Processinformation i Goteborg AB"},
      {"PIK", "pikkerton GmbH"},
      {"PIL", "Pilot Systems (London) Ltd"},
      {"PIM", "Power Innovation GmbH"},
      {"PIN", "PFIFFNER Instr. Transformers private"},
      {"PIP", "Hermann Pipersberg jr."},
      {"PIV", "Pivot Access Ltd."},
      {"PLL", "POLL, s.r.o."},
      {"PLN", "Prolan Process Control Company"},
      {"PLO", "Weihai Ploumeter Co. Ltd."},
      {"PLU", "Plutus Smart Energy Solutions Pvt. Ltd."},
      {"PME", "Pal Mohan Electronics Pvt Ltd"},
      {"PMG", "Sensus Metering Systems"},
      {"PML", "PROGRESSIVE METERS PVT LTD."},
      {"PMP", "REDUR GmbH & Co. KG"},
      {"PMS", "PMS-Elektronik GmbH"},
      {"PMX", "Dell`Anna Ing. Luca"},
      {"PNC", "PNC Technology Co., Ltd"},
      {"PNG", "PAKTIM METERING NIGERIA LTD"},
      {"POD", "PowerOneData"},
      {"POL", "Pronal Sp. z o.o. sp.k."},
      {"POW", "PowerApp"},
      {"POZ", "ZEUP Pozyton sp. z o.o."},
      {"PPC", "Power Plus Communications AG"},
      {"PPL", "Prompribor plant Limited"},
      {"PPS", "Palace Power Systems"},
      {"PQP", "PQ Plus GmbH"},
      {"PRA", "Paya Ravesh Aria"},
      {"PRE", "Predicate Software"},
      {"PRG", "Paud Raad Industrial Group"},
      {"PRI", "Polymeters Response International Ltd."},
      {"PRM", "Promatic d.o.o."},
      {"PRO", "Proton - Elektromed Ltd"},
      {"PRY", "ShanDong LiChuang Science and Technology Co.,Ltd."},
      {"PSE", "pSenso sp. z o.o."},
      {"PSN", "PySENSE Sp. z o.o."},
      {"PST", "PSTec Co.,Ltd"},
      {"PTI", "Prolific Technology Inc."},
      {"PTR", "Pfiffner Transformatör A.S."},
      {"PUK", "Paktim Consulting UK Ltd"},
      {"PUL", "NPP Teplovodokhran Ltd"},
      {"PVT", "Pavo Tasarım Üretim Elektronik Tic. A.Ş."},
      {"PWB", "Paul Wegener GmbH"},
      {"PWR", "Powrtec"},
      {"PXC", "Phoenix Contact GmbH & Co. KG"},
      {"PYU", "PYUNGIL Co. Ltd"},
      {"PYX", "Pyrexx GmbH"},
      {"QDR", "Quadrar Tecnologia"},
      {"QDS", "Qundis GmbH"},
      {"QFP", "QFP Engineering"},
      {"QSD", "Quicksand"},
      {"QTS", "QT systems ab"},
      {"RAC", "Michael Rac GmbH"},
      {"RAD", "Radiocrafts AS"},
      {"RAM", "Rossweiner Armaturen und Messgeräte GmbH & Co. OHG"},
      {"RAS", "Rubikon Apskaitos Sistemos"},
      {"RAY", "Rayleigh Instruments Limited"},
      {"RBM", "R.B.M. S.p.A"},
      {"RCE", "RC ENERGY METERING PVT,LTD."},
      {"RDK", "Wuhan Radarking Electronics Corp."},
      {"RDM", "RDMx Consulting"},
      {"REC", "Zhejiang Reallin Electron Co. Ltd."},
      {"REF", "REFERANS ELEKTRIK SAYACLARI A.S."},
      {"REI", "RENESAS ELECTRONICS INDIA PRIVATE LIMITED"},
      {"REL", "Relay GmbH"},
      {"REM", "Remote Energy Monitoring"},
      {"REP", "Radiant Energy Solutions Pvt Ltd"},
      {"RES", "Renesas Electronics Singapore Pte Ltd"},
      {"RHN", "Rhino"},
      {"RIC", "Richa Equipments Pvt. Ltd."},
      {"RIL", "Rikken Instrumentation Limited"},
      {"RIM", "CJSC \"Radio and Microelectronics\""},
      {"RIN", "Rayleigh Instruments Ltd"},
      {"RIT", "Ritz Instrument Transformers GmbH"},
      {"RIX", "Raonix Co., Ltd."},
      {"RIZ", "RIZ Transmitters"},
      {"RKE", "Viterra Energy Services (formerly Raab Karcher ES)"},
      {"RMA", "Mess- und Regeltechnik GmbH & Co. KG"},
      {"RMG", "RMG Messtechnik GmbH"},
      {"RMI", "Racemosa Energy India Pvt Ltd"},
      {"RML", "ROLEX METERS RPIVATE LIMITED"},
      {"RMR", "Advanced Technology RAMAR"},
      {"RMT", "Richter Messtechnik GmbH & Co.KG"},
      {"RNW", "Renergy Micro-Technologies"},
      {"ROK", "“ROKIP” Limited Liability Company"},
      {"RSA", "Rahrovan Sepehr Andisheh  Pte. Co."},
      {"RSM", "Zhejiang Risesun Science and Technology Co.,Ltd."},
      {"RSW", "RSW Technik GmbH"},
      {"SAA", "Sanjesh Afzar Asia Ltd. Co."},
      {"SAC", "SACOFGAS srl"},
      {"SAE", "SAE IT-systems GmbH & Co. KG"},
      {"SAG", "Sagemcom Energy & Telecom"},
      {"SAL", "Salzer Electronics Limited"},
      {"SAM", "Siemens AG Österreich, AMIS (Automated Metering and Information System)"},
      {"SAN", "SANN Stockholm AB"},
      {"SAP", "Sappel "},
      {"SAT", "SATEC Ltd"},
      {"SBC", "Saia-Burgess Controls "},
      {"SCA", "SENECA srl"},
      {"SCE", "Seo Chang Electric Communication Co Ltd"},
      {"SCH", "Schinzel GmbH"},
      {"SCL", "Steama Company Limited"},
      {"SCM", "CalinMeter Co. ltd."},
      {"SCR", "Sanchuan Wisdom Technology Co., Ltd."},
      {"SCT", "S.I.C.E. Telecomunicazioni Srl"},
      {"SCW", "ScatterWeb GmbH"},
      {"SDC", "SdC – Sistemas de Contagem"},
      {"SDM", "Shandong Delu Measurement Co., Ltd."},
      {"SDS", "Sitec s.r.l Elettronica industriale"},
      {"SEC", "Schneider Electric Canada"},
      {"SEE", "El Sewedy Electrometer Egypt"},
      {"SEH", "SAMRAKSHANA ELECTRICALS LTD"},
      {"SEI", "Sicom Electronics International S.A."},
      {"SEK", "StroyEnergoKom Ltd."},
      {"SEL", "Selec Controls Pvt Ltd"},
      {"SEM", "Smart Meter Company Limited"},
      {"SEN", "Sensus Metering Systems"},
      {"SEO", "SENSOCO Greatech GmbH"},
      {"SET", "Sagemcom Energy & Telecom"},
      {"SFI", "Siemens AG - DI PA MI"},
      {"SFT", "Sotflink s.r.o"},
      {"SGA", "smartGAS Mikrosensorik GmbH"},
      {"SGI", "Smartgrid Innovations Pvt Ltd"},
      {"SGM", "Swiss Gas Metering AG"},
      {"SGN", "SYGNITY S.A."},
      {"SGX", "Gao Xiang Water Meter Co. Ltd."},
      {"SHD", "Beijing SanHuaDeBao Energy Technoligy Co.,Ltd."},
      {"SHE", "Shenzhen SingHang Elec-tech Co., Ltd."},
      {"SHM", "Shanghai Metering, China"},
      {"SHT", "Shitek Technology srl"},
      {"SIC", "SICK Engineering GmbH"},
      {"SIE", "Siemens AG"},
      {"SIG", "Sigrenea"},
      {"SIJ", "SUN STAR INDUSTRIES"},
      {"SIL", "Silicon Laboratories"},
      {"SIM", "Sana Intelligent Meter"},
      {"SIN", "SINAPSI SRL"},
      {"SIS", "Sevme Informatique Service"},
      {"SIT", "SITEL doo"},
      {"SIV", "Sieverding Heizungs- und Sanitaertechnik GmbH"},
      {"SIX", "Six Innovation AB"},
      {"SJA", "Sheng Jay Automation Technologies Co., Ltd."},
      {"SKI", "S.K.I. GmbH"},
      {"SKK", "Shikoku Instrumentation Co.,Ltd."},
      {"SKN", "BENTEX CONTROL AND SWITCH GEAR CO."},
      {"SKQ", "SKI( sherkate kontorsazi Iran)"},
      {"SKT", "SkyToll a.s."},
      {"SKY", "SKYLARK SMARTMETERS PVT LTD"},
      {"SLB", "Schlumberger Industries Ltd."},
      {"SLG", "Silergy Technologies"},
      {"SLP", "Sylop spółka z ograniczoną odpowiedzialnością sp.k."},
      {"SLV", "Solvimus GmbH"},
      {"SLW", "SOLID WAY SAS"},
      {"SLX", "Ymatron AG"},
      {"SMA", "Smart-me AG"},
      {"SMC", "Sierra Monitor Corporation"},
      {"SME", "Siame"},
      {"SMF", "Star Measure"},
      {"SMG", "Samgas s.r.l. "},
      {"SMI", "PT. SMART METER INDONESIA"},
      {"SML", "Siemens Measurements Ltd."},
      {"SMM", "Smart Metering S.r.l."},
      {"SMN", "Saiman Corporation LLC"},
      {"SMP", "LLC FIRM SEMPAL CO LTD"},
      {"SMQ", "SMARTMETERQ srl"},
      {"SMR", "Saudi Meters Company Ltd"},
      {"SMS", "Smart Metering Solutions (Changsha) Co. Ltd."},
      {"SMT", "Smarteh d.o.o."},
      {"SMX", "Smart Meters Technologies Sdn Bhd"},
      {"SNB", "Stromnetz Berlin GmbH"},
      {"SNM", "ShenZhen Northmeter Co.Ltd "},
      {"SNR", "NTN-SNR"},
      {"SNS", "Signals and Systems India Private Limited"},
      {"SNT", "SensorNet s.r.l."},
      {"SOC", "SOCOMEC"},
      {"SOF", "Softflow.de GmbH"},
      {"SOG", "Sogecam Industrial, S.A."},
      {"SOL", "Soledia Srl"},
      {"SOM", "Somesca"},
      {"SON", "Sontex SA"},
      {"SOS", "SOFTSERVICE"},
      {"SOT", "Sotronix"},
      {"SPC", "JSC RPC Spektr"},
      {"SPE", "SUKHILA POWER ELECTRONICS PVT LTD"},
      {"SPL", "Sappel"},
      {"SPM", "Stelmec Powercom Private Limited"},
      {"SPX", "Sensus Metering Systems"},
      {"SPZ", "SPowerZ Solutions Pvt Ltd"},
      {"SRE", "Guangzhou Sunrise Electronics Development Co., Ltd., "},
      {"SRF", "Saraf Industries"},
      {"SRN", "Shandong SARON Intelligent Technology Co., Ltd."},
      {"SRV", "Servic LLC"},
      {"SSE", "S&T Smart Energy GmbH"},
      {"SSG", "Super Star Electronics Limited"},
      {"SSI", "Security Solutions Institute LTD"},
      {"SSL", "Synapsys Solutions Ltd."},
      {"SSM", "SCC METERS LTD."},
      {"SSN", "Silver Spring Networks"},
      {"SSS", "SUEZ SMART SOLUTIONS"},
      {"SST", "Qingdao Haina Electric Automation Systems Co., Ltd."},
      {"STA", "Shenzhen Star Instrument Co Ltd"},
      {"STC", "Sunrise Technology Co., Ltd"},
      {"STD", "Stedin B.V"},
      {"STE", "Satera Elektrik Elektronik San. ve Tic. A.S."},
      {"STF", "STACKFORCE GmbH"},
      {"STL", "Saudi Technical Group"},
      {"STM", "STELMEC LTD"},
      {"STO", "ABB STOTZ-KONTAKT GmbH"},
      {"STP", "Spectrum Tool Engineers Pvt, Ltd."},
      {"STR", "Strike Technologies"},
      {"STS", "Swistec Systems AG"},
      {"STV", "STV Automation, Branch of STV Electronic"},
      {"STW", "Siterwell Electronics CO. Limited"},
      {"STZ", "Steinbeis Innovation Center Embedded Design and Networking"},
      {"SUL", "SINHAL UDYOG PRIVATE LIMITED"},
      {"SUM", "Sumeru Verrdhe Technologies Pvt Ltd"},
      {"SUN", "TIAN JIN SUN ENERGY TECHNOLOGY CO. LTD."},
      {"SUX", "Supermax Components Pvt Ltd"},
      {"SVM", "AB Svensk Värmemätning SVM"},
      {"SVT", "SPUTNIK"},
      {"SWI", "Swistec GmbH"},
      {"SWM", "Smart Water Metering Inc."},
      {"SWS", "Stadtwerke Senftenberg GmbH"},
      {"SWT", "Beijing Swirling Technology Co. Ltd"},
      {"SYC", "Sycous Limited, Leeds Innovation Centre"},
      {"SYD", "Sydler Electronics Pvt Ltd"},
      {"SYN", "SMSISTEM Ltd."},
      {"SYS", "Softwareentwicklung & Systemdesign"},
      {"SYX", "SyxthSense Ltd"},
      {"SZS", "Szerver Szektor Kft."},
      {"TAG", "Telma AG"},
      {"TAL", "TALAMONA S.r.l."},
      {"TAN", "Tianxin instrument group co. LTD"},
      {"TAS", "Pouyeshgaran Tabriz Azma"},
      {"TAT", "Tatung Co."},
      {"TAU", "TARGUS TECHNOLOGIES PVT. LTD."},
      {"TAY", "Taytech Otomasyon ve Bilisim Teknolojileri LTD. Sti"},
      {"TAZ", "PoyeshGaran  Sahandzaran Tabrizazma"},
      {"TBN", "TBEA Nanjing Intelligent Electric Co., Ltd."},
      {"TBS", "TEBAŞ END. ISI SİS İNŞ TUR SAN VE TİC LTD ŞTİ"},
      {"TCE", "Qingdao iTechene Technologies Co., Ltd."},
      {"TCH", "Techem"},
      {"TCM", "TCOM doo"},
      {"TCO", "Teco a.s."},
      {"TCP", "Telecard-Prilad LLC"},
      {"TCT", "Tecnotel Srl"},
      {"TCX", "Qingdao Topscomm Communication Co.,Ltd"},
      {"TCZ", "Tianjin Chuangzhan Tongcheng Technology Development Co.,Ltd."},
      {"TDC", "Telecom Design"},
      {"TEA", "TEAM-R"},
      {"TEC", "TECSON Digital"},
      {"TEH", "IOTech LTD"},
      {"TEI", "Tohoku Electric Meter Industry Co.,Inc."},
      {"TEK", "Tekmar Regelsysteme GmbH"},
      {"TEN", "TekhnoEnergo LLC"},
      {"TEO", "ubitricity Gesellschaft für verteilte Energiesysteme mbH"},
      {"TEP", "TEPEECAL"},
      {"TER", "Tavrida Electric Russia"},
      {"TEU", "TOSHELECTROAPPARAT LLC FE"},
      {"TFC", "Toos Fuse Co."},
      {"TFG", "TERMICS s.r.l. Divisione FIMIGAS"},
      {"TGX", "Tiesse Spa"},
      {"THE", "Theben AG"},
      {"THW", "TW-TEAMWARE"},
      {"TIC", "TOKYO KEISO CO.,LTD."},
      {"TID", "TIDE Co.,Ltd"},
      {"TIG", "ZHONGHUAN-TIG CO.,LTD"},
      {"TII", "TRIKALA INDUSTRIES INDIA PVT LTD"},
      {"TIL", "Thermal Integration Limited"},
      {"TIP", "TIP GmbH"},
      {"TIS", "Texas Instruments (Hong Kong) Ltd."},
      {"TIX", "Tixi.Com GmbH"},
      {"TKN", "TECHKNAVE"},
      {"TKS", "Teksan Teknolojik Ölçüm Sistemleri A.Ş."},
      {"TLC", "TELECON GALICIA,S.A."},
      {"TLM", "Theodor Lange Messgeräte GmbH"},
      {"TLR", "Telereading srl"},
      {"TLS", "TLS Energimätning AB"},
      {"TLT", "Telecommunication Technologies LLC"},
      {"TLY", "LLC «SPE» Telemetry»"},
      {"TME", "TECHNO METERS & ELECTRONICS"},
      {"TMK", "Timi Kosova Sh.p.k."},
      {"TMS", "TEMASS IMALAT A.S"},
      {"TMZ", "TMZ - Thüringer Mess- und Zählerwesen Service GmbH"},
      {"TOE", "Top For Electrical Industries"},
      {"TOP", "KMB systems, s.r.o."},
      {"TPB", "2 Plus Bulgaria AD"},
      {"TPC", "Taipit - measuring equipment"},
      {"TPG", "Texnopark"},
      {"TPI", "Transfopower Industries (Pvt.) Ltd."},
      {"TPJ", "TAKAHATA PRECISION JAPAN CO., LTD."},
      {"TPL", "Teplocom Holding"},
      {"TPZ", "PLC Technology"},
      {"TRC", "Traco Doo"},
      {"TRG", "Trench Germany GmbH"},
      {"TRI", "Tritech Technology AB"},
      {"TRJ", "SHENZHEN TECHRISE ELECTRONICS CO.,LTD"},
      {"TRL", "Trilliant Inc."},
      {"TRN", "TERRANOVA SRL"},
      {"TRO", "TROX GmbH"},
      {"TRU", "Truteq Wireless"},
      {"TRV", "Transvaro Elektron Aletleri A.S."},
      {"TRW", "Triowatt GmbH"},
      {"TRX", "Beijing TianRuiXiang Equipment Co.,Ltd."},
      {"TRZ", "TR Group (Pty) Ltd"},
      {"TSD", "Theobroma Systems Design und Consulting GmbH"},
      {"TSE", "Nichi Manufacturing Pvt. Ltd."},
      {"TSG", "Testo Sensor GmbH"},
      {"TSW", "T7 WENMAX SDN. BHD."},
      {"TTG", "Tatung Co."},
      {"TTM", "Toshiba Toko Meter Systems Co., Ltd."},
      {"TTN", "Tatung Co."},
      {"TTR", "Tetraedre Sarl"},
      {"TTT", "Telephone and Telegraph Technique Plc"},
      {"TUR", "TURKSAY ELEKTRONIK ELEKTRIK ENDUSTRISI"},
      {"TWO", "2Flow AB"},
      {"TXL", "CETC46 TianJin New Top Electronics Technology Co.,Ltd."},
      {"UAG", "Uher"},
      {"UBI", "Ubitronix system solutions gmbh"},
      {"UBY", "ubitricity - Gesellschaft für verteilte Energiesysteme mbH"},
      {"UEI", "United Electrical Industries Limited"},
      {"UEL", "united electrical industries ltd"},
      {"UGI", "United Gas Industries"},
      {"UGT", "DP UKRGAZTECH Ltd. (Ukrainian gas technologies)"},
      {"UHM", "Micronics Ltd."},
      {"UNI", "Univations Limited"},
      {"URM", "Urmet Telecomunicazioni SPA"},
      {"USC", "Usanca Soluciones S.L."},
      {"UTF", "UtiliFlex"},
      {"UTI", "Utilia Spa"},
      {"UTL", "United Telecoms Limited"},
      {"UTT", "UtiliTools GmbH"},
      {"VAL", "Valkoder OOD"},
      {"VAR", "VARAAHI ELECTROMECH PRIVATE LIMITED"},
      {"VDP", "Plant Vodopribor management company"},
      {"VEC", "Energo Control LLC"},
      {"VEL", "VELANKANI ELECTRONICS PRIVATE LIMITED"},
      {"VEN", "INVENDIS TECHNOLOGIES INDIA PVT LTD"},
      {"VER", "VERAUT GmbH"},
      {"VES", "Viterra Energy Services"},
      {"VEX", "Vertex Electronics (Pvt) Ltd."},
      {"VGO", "Vango Technologies, Inc."},
      {"VIE", "Vientech"},
      {"VIK", "VI-KO ELEKTRIK"},
      {"VIM", "VİEN ENERJİ SİSTEMLERİ SANAYİ VE TİCARET LİMİTED ŞİRKETİ"},
      {"VIN", "Vektor innovations private limited"},
      {"VIP", "VIPA CZ s.r.o."},
      {"VIT", "Vitir AS"},
      {"VLT", "ABB s.r.o., EPMV Division"},
      {"VMP", "VAMP Oy."},
      {"VNE", "Vision Networks"},
      {"VPI", "Van Putten Instruments B.V."},
      {"VPL", "Verticross India Private Limited"},
      {"VSE", "Valenciana Smart Energy of Mediterranean Sea S.A"},
      {"VSN", "Viewshine Ltd."},
      {"VTC", "Vitelec"},
      {"VTG", "vemm tec Messtechnik GmbH"},
      {"VTK", "Linkwell Telesystems Pvt. Ltd."},
      {"VTN", "VITEX NOVA"},
      {"VTZ", "VitzroSys Co., Ltd."},
      {"VVV", "VIVAVIS AG"},
      {"WAD", "Waher Data AB"},
      {"WAH", "WAHESOFT UG"},
      {"WAI", "Chongqing WECAN Precision Instruments Co.,Ltd."},
      {"WAL", "Wallaby Metering Systems Pvt. Ltd."},
      {"WDN", "Webdyn SA"},
      {"WEB", "Webolution GmbH & Co. KG"},
      {"WEG", "WEG Equipamentos Elétricos S.A. – Automação"},
      {"WEH", "E. Wehrle GmbH"},
      {"WEL", "WELLTECH automation"},
      {"WEP", "Weptech elektronik GmbH"},
      {"WFT", "Waft Embedded Circuit Solutions"},
      {"WGN", "Wasser-Geräte GmbH"},
      {"WGP", "GreenPoint sp. z o.o."},
      {"WIG", "Wigersma & Sikkema"},
      {"WIK", "WIKON Kommunikationstechnik GmbH"},
      {"WIN", "Windmill Innovations BV"},
      {"WKL", "Shenyang jia DE lian yi energy technology co., LTD"},
      {"WKX", "JINING WUKEXING METER CO. LTD."},
      {"WMO", "Westermo Teleindustri AB"},
      {"WNC", "wireless-netcontrol GmbH"},
      {"WNW", "Wistron NeWeb Corporation, Marketing Center"},
      {"WOW", "Sciknow Techno Solutions Ltd"},
      {"WSD", "Yantai Wisdom Electric Co., Ltd."},
      {"WSE", "Wasion Group Co.Ltd"},
      {"WSG", "ZHEJIANG WELLSUN INTELLIGENT TECHNOLOGY CO., LTD"},
      {"WSM", "winAMR Systems Private Limited"},
      {"WSR", "OOO WESER"},
      {"WTI", "Weihai Sunts Electric Meter Co., Ltd."},
      {"WTL", "Wipro Technologies"},
      {"WTM", "Watertech S.r.l."},
      {"WTT", "Watertech S.r.l."},
      {"WUR", "Wurm GmbH & Co. KG Elektronische Systeme"},
      {"WZG", "Neumann & Co. Wasserzähler Glaubitz GmbH"},
      {"WZT", "Wizit Co. Ltd."},
      {"XAO", "Info Solution SpA"},
      {"XEM", "XEMTEC AG"},
      {"XIO", "XIOTA India Pvt. Ltd"},
      {"XJM", "XJ Metering Co. Ltd."},
      {"XMA", "XMASTER s.c. ul."},
      {"XMX", "Xemex NV"},
      {"XTM", "Suntront Tech Co. Ltd."},
      {"XTR", "HENAN SUNTRONT TECH CO. LTD."},
      {"XTY", "LianYuanGang Tengyue Electronics & Technology Co. Ltd."},
      {"XYL", "Sensus GmbH Ludwigshafen"},
      {"YDD", "Jilin Yongda Group Co. Ltd."},
      {"YDS", "YIDU Smart Technology ( Beijing ) Co. Ltd."},
      {"YFC", "Yufeng Changhui Automation Instrument Co. Ltd."},
      {"YGM", "YGM, Shandong Yiguang heat metering technology CO. LTD."},
      {"YHE", "Youho Electric Co. Ltd."},
      {"YJZ", "Zhuhai Yujian Science & Technology Co., Ltd"},
      {"YNE", "YOONO ENERGY TECHNOLOGY (JIANGSU) CO., LTD."},
      {"YNP", "Ningbo Yong Neng Power Technology Co. Ltd."},
      {"YPP", "YPP Corp"},
      {"YSS", "Yellowstone Soft"},
      {"YTE", "Yuksek Teknoloji"},
      {"YTL", "ZheJiang yongtailong electronic co.,ltd."},
      {"YYW", "Shandong youyuan instrument co. LTD"},
      {"YZR", "Cangzhou City Hebei Electronic Technology Co. Ltd."},
      {"ZAG", "Zellweger Uster AG"},
      {"ZAP", "Zaptronix"},
      {"ZAR", "SNC ZARALAB"},
      {"ZCH", "Zhejiang Chaorong Electric Technology Co., Ltd"},
      {"ZEL", "Dr. techn. Josef Zelisko GmbH"},
      {"ZEN", "ZenMeter Solutions Pvt. Ltd."},
      {"ZEX", "ZEXON ENERGY PRIVATE LIMITED"},
      {"ZFY", "Hang Zhou Fu Yang Instrument General Factory"},
      {"ZGX", "ZIGNUX TECHNOLOGY S.L."},
      {"ZIP", "St. Petersburg Meters\` Factory Co., Ltd."},
      {"ZIV", "ZIV Aplicaciones y Tecnologia, S.A."},
      {"ZJY", "Zhejiang Jiayou Thermal Technology Equipment Co. LTD."},
      {"ZOT", "Zhejiang Ocaenergy Technology Co., Ltd"},
      {"ZPA", "ZPA Smart Energy a.s."},
      {"ZRI", "ZENNER International GmbH & Co. KG"},
      {"ZRM", "ZENNER International GmbH & Co. KG"},
      {"ZTE", "ZTE Corporation ZTE Plaza"},
      {"ZTX", "ZHEJIANG TANCY INSTRUMENT TECHNOLOGY CO. éTD-"},
      {"ZTY", "ZHEJIANG CHINT INSTRUMENT & METER CO. LTD."},
      {"ZVC", "SigmaHeat GmbH"},
      {"ZXT", "Zhejiang Xinghao Technology Co., Ltd"},
      {"ZXY", "Linyi City Xiaoyuan Water Meter Co., Ltd."},
      {"ZYB", "WEIHAI ZHENYU INTELL & TECH Co. Ltd."},
      {"ZYS", "Wuxi Zhongyi Smart Technology CO,. LTD"},
      {"ZZZ", "Michael Rac GmbH"},
    };
  }
}